export const QUESTION_CATEGORIES = Object.freeze({
    GENERAL_KNOWLEDGE: { ID: 9, LABEL: 'General Knowledge' },
    BOOKS: { ID: 10, LABEL: 'Books' },
    MOVIES: { ID: 11, LABEL: 'Movies' },
    MUSIC: { ID: 12, LABEL: 'Music' },
    MUSICALS_THEATRES: { ID: 13, LABEL: 'Musicals Theatres' },
    TELEVISION: { ID: 14, LABEL: 'Television' },
    VIDEO_GAMES: { ID: 15, LABEL: 'Video Games' },
    BOARD_GAMES: { ID: 16, LABEL: 'Board games' },
    SCIENCE_NATURE: { ID: 17, LABEL: 'Science & Nature' },
    COMPUTERS: { ID: 18, LABEL: 'Computers' },
    MATHEMATICS: { ID: 19, LABEL: 'Mathematics' },
    MYTHOLOGY: { ID: 20, LABEL: 'Mythology' },
    SPORTS: { ID: 21, LABEL: 'Sports' },
    GEOGRAPHY: { ID: 22, LABEL: 'Geography' },
    HISTORY: { ID: 23, LABEL: 'History' },
    POLITICS: { ID: 24, LABEL: 'Politics' },
    ART: { ID: 25, LABEL: 'Art' },
    CELEBRITIES: { ID: 26, LABEL: 'Celebrities' },
    ANIMALS: { ID: 27, LABEL: 'Animals' },
    VEHICLES: { ID: 28, LABEL: 'Vehicles' },
    COMICS: { ID: 29, LABEL: 'Comics' },
    GADGETS: { ID: 30, LABEL: 'Gadgets' },
    JAPANESE_ANIME_MANGA: { ID: 31, LABEL: 'Japanese Anime & Manga' },
    CARTOON_ANIMATIONS: { ID: 32, LABEL: 'Cartoon & Animations' },
})
