export const CREATE_QUESTION_PAGE_STRINGS = Object.freeze({
    TITLE: 'Create a question',
    QUESTION_INPUT_LABEL: 'Question',
    QUESTION_INPUT_REQUIRED: 'Please inform the question',
    CATEGORY_INPUT_LABEL: 'Category',
    CATEGORY_INPUT_REQUIRED: 'Please inform a category',
    DIFFICULTY_INPUT_LABEL: 'Difficulty',
    DIFFICULTY_INPUT_REQUIRED: 'Please inform the difficulty',
    TYPE_INPUT_LABEL: 'Type',
    TYPE_INPUT_REQUIRED: 'Please inform the question type',
    CORRECT_ANSWER_LABEL: 'Correct answer',
    CORRECT_ANSWER_REQUIRED: 'Please inform the correct answer',
    INCORRECT_ANSWERS_LABEL: 'Incorrect answers',
    INCORRECT_ANSWERS_REQUIRED: 'Please inform all the incorrect answers',
    TRUE_RADIO_LABEL: 'True',
    FALSE_RADIO_LABEL: 'False',
    CREATE_BUTTON_LABEL: 'Create',
    SUCCESS_TOAST_MESSAGE: 'Question created successfully!',
})
